import React from 'react';
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import "./globals.css";

import { Montserrat } from 'next/font/google';
import localFont from "next/font/local";
import Script from 'next/script'
import { AnimatePresence } from 'framer-motion';

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mont"
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased bg-light font-mont w-full min-h-screen dark:bg-dark`}
      >
        <Script strategy='beforeInteractive'>
          {`          
          document.documentElement.classList.toggle(
  'dark',
  localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)
)
`}
        </Script>
        <NavBar />
        <AnimatePresence mode="wait"> 
        {children}
        </AnimatePresence>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
